// Code generated by mockery. DO NOT EDIT.

package biz

import (
	biz "github.com/acepanel/panel/v3/internal/biz"
	mock "github.com/stretchr/testify/mock"

	request "github.com/acepanel/panel/v3/internal/request"
)

// WafRepo is an autogenerated mock type for the WafRepo type
type WafRepo struct {
	mock.Mock
}

type WafRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *WafRepo) EXPECT() *WafRepo_Expecter {
	return &WafRepo_Expecter{mock: &_m.Mock}
}

// AttackMap provides a mock function with given fields: query
func (_m *WafRepo) AttackMap(query map[string]string) (interface{}, error) {
	ret := _m.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for AttackMap")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(map[string]string) (interface{}, error)); ok {
		return rf(query)
	}
	if rf, ok := ret.Get(0).(func(map[string]string) interface{}); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(map[string]string) error); ok {
		r1 = rf(query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WafRepo_AttackMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttackMap'
type WafRepo_AttackMap_Call struct {
	*mock.Call
}

// AttackMap is a helper method to define mock.On call
//   - query map[string]string
func (_e *WafRepo_Expecter) AttackMap(query interface{}) *WafRepo_AttackMap_Call {
	return &WafRepo_AttackMap_Call{Call: _e.mock.On("AttackMap", query)}
}

func (_c *WafRepo_AttackMap_Call) Run(run func(query map[string]string)) *WafRepo_AttackMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[string]string))
	})
	return _c
}

func (_c *WafRepo_AttackMap_Call) Return(_a0 interface{}, _a1 error) *WafRepo_AttackMap_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WafRepo_AttackMap_Call) RunAndReturn(run func(map[string]string) (interface{}, error)) *WafRepo_AttackMap_Call {
	_c.Call.Return(run)
	return _c
}

// CreateDecision provides a mock function with given fields: req
func (_m *WafRepo) CreateDecision(req *request.WafDecisionCreate) (interface{}, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for CreateDecision")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(*request.WafDecisionCreate) (interface{}, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*request.WafDecisionCreate) interface{}); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(*request.WafDecisionCreate) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WafRepo_CreateDecision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDecision'
type WafRepo_CreateDecision_Call struct {
	*mock.Call
}

// CreateDecision is a helper method to define mock.On call
//   - req *request.WafDecisionCreate
func (_e *WafRepo_Expecter) CreateDecision(req interface{}) *WafRepo_CreateDecision_Call {
	return &WafRepo_CreateDecision_Call{Call: _e.mock.On("CreateDecision", req)}
}

func (_c *WafRepo_CreateDecision_Call) Run(run func(req *request.WafDecisionCreate)) *WafRepo_CreateDecision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*request.WafDecisionCreate))
	})
	return _c
}

func (_c *WafRepo_CreateDecision_Call) Return(_a0 interface{}, _a1 error) *WafRepo_CreateDecision_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WafRepo_CreateDecision_Call) RunAndReturn(run func(*request.WafDecisionCreate) (interface{}, error)) *WafRepo_CreateDecision_Call {
	_c.Call.Return(run)
	return _c
}

// CreateExclusion provides a mock function with given fields: policyID, body
func (_m *WafRepo) CreateExclusion(policyID string, body interface{}) (interface{}, error) {
	ret := _m.Called(policyID, body)

	if len(ret) == 0 {
		panic("no return value specified for CreateExclusion")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(string, interface{}) (interface{}, error)); ok {
		return rf(policyID, body)
	}
	if rf, ok := ret.Get(0).(func(string, interface{}) interface{}); ok {
		r0 = rf(policyID, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(string, interface{}) error); ok {
		r1 = rf(policyID, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WafRepo_CreateExclusion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateExclusion'
type WafRepo_CreateExclusion_Call struct {
	*mock.Call
}

// CreateExclusion is a helper method to define mock.On call
//   - policyID string
//   - body interface{}
func (_e *WafRepo_Expecter) CreateExclusion(policyID interface{}, body interface{}) *WafRepo_CreateExclusion_Call {
	return &WafRepo_CreateExclusion_Call{Call: _e.mock.On("CreateExclusion", policyID, body)}
}

func (_c *WafRepo_CreateExclusion_Call) Run(run func(policyID string, body interface{})) *WafRepo_CreateExclusion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(interface{}))
	})
	return _c
}

func (_c *WafRepo_CreateExclusion_Call) Return(_a0 interface{}, _a1 error) *WafRepo_CreateExclusion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WafRepo_CreateExclusion_Call) RunAndReturn(run func(string, interface{}) (interface{}, error)) *WafRepo_CreateExclusion_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePolicy provides a mock function with given fields: body
func (_m *WafRepo) CreatePolicy(body interface{}) (interface{}, error) {
	ret := _m.Called(body)

	if len(ret) == 0 {
		panic("no return value specified for CreatePolicy")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}) (interface{}, error)); ok {
		return rf(body)
	}
	if rf, ok := ret.Get(0).(func(interface{}) interface{}); ok {
		r0 = rf(body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WafRepo_CreatePolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePolicy'
type WafRepo_CreatePolicy_Call struct {
	*mock.Call
}

// CreatePolicy is a helper method to define mock.On call
//   - body interface{}
func (_e *WafRepo_Expecter) CreatePolicy(body interface{}) *WafRepo_CreatePolicy_Call {
	return &WafRepo_CreatePolicy_Call{Call: _e.mock.On("CreatePolicy", body)}
}

func (_c *WafRepo_CreatePolicy_Call) Run(run func(body interface{})) *WafRepo_CreatePolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *WafRepo_CreatePolicy_Call) Return(_a0 interface{}, _a1 error) *WafRepo_CreatePolicy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WafRepo_CreatePolicy_Call) RunAndReturn(run func(interface{}) (interface{}, error)) *WafRepo_CreatePolicy_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDecision provides a mock function with given fields: query
func (_m *WafRepo) DeleteDecision(query map[string]string) error {
	ret := _m.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDecision")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]string) error); ok {
		r0 = rf(query)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WafRepo_DeleteDecision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDecision'
type WafRepo_DeleteDecision_Call struct {
	*mock.Call
}

// DeleteDecision is a helper method to define mock.On call
//   - query map[string]string
func (_e *WafRepo_Expecter) DeleteDecision(query interface{}) *WafRepo_DeleteDecision_Call {
	return &WafRepo_DeleteDecision_Call{Call: _e.mock.On("DeleteDecision", query)}
}

func (_c *WafRepo_DeleteDecision_Call) Run(run func(query map[string]string)) *WafRepo_DeleteDecision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[string]string))
	})
	return _c
}

func (_c *WafRepo_DeleteDecision_Call) Return(_a0 error) *WafRepo_DeleteDecision_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WafRepo_DeleteDecision_Call) RunAndReturn(run func(map[string]string) error) *WafRepo_DeleteDecision_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExclusion provides a mock function with given fields: policyID, query
func (_m *WafRepo) DeleteExclusion(policyID string, query map[string]string) error {
	ret := _m.Called(policyID, query)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExclusion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, map[string]string) error); ok {
		r0 = rf(policyID, query)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WafRepo_DeleteExclusion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExclusion'
type WafRepo_DeleteExclusion_Call struct {
	*mock.Call
}

// DeleteExclusion is a helper method to define mock.On call
//   - policyID string
//   - query map[string]string
func (_e *WafRepo_Expecter) DeleteExclusion(policyID interface{}, query interface{}) *WafRepo_DeleteExclusion_Call {
	return &WafRepo_DeleteExclusion_Call{Call: _e.mock.On("DeleteExclusion", policyID, query)}
}

func (_c *WafRepo_DeleteExclusion_Call) Run(run func(policyID string, query map[string]string)) *WafRepo_DeleteExclusion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(map[string]string))
	})
	return _c
}

func (_c *WafRepo_DeleteExclusion_Call) Return(_a0 error) *WafRepo_DeleteExclusion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WafRepo_DeleteExclusion_Call) RunAndReturn(run func(string, map[string]string) error) *WafRepo_DeleteExclusion_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePolicy provides a mock function with given fields: policyID
func (_m *WafRepo) DeletePolicy(policyID string) error {
	ret := _m.Called(policyID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePolicy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(policyID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WafRepo_DeletePolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePolicy'
type WafRepo_DeletePolicy_Call struct {
	*mock.Call
}

// DeletePolicy is a helper method to define mock.On call
//   - policyID string
func (_e *WafRepo_Expecter) DeletePolicy(policyID interface{}) *WafRepo_DeletePolicy_Call {
	return &WafRepo_DeletePolicy_Call{Call: _e.mock.On("DeletePolicy", policyID)}
}

func (_c *WafRepo_DeletePolicy_Call) Run(run func(policyID string)) *WafRepo_DeletePolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *WafRepo_DeletePolicy_Call) Return(_a0 error) *WafRepo_DeletePolicy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WafRepo_DeletePolicy_Call) RunAndReturn(run func(string) error) *WafRepo_DeletePolicy_Call {
	_c.Call.Return(run)
	return _c
}

// DisableWebsite provides a mock function with given fields: websiteID
func (_m *WafRepo) DisableWebsite(websiteID uint) error {
	ret := _m.Called(websiteID)

	if len(ret) == 0 {
		panic("no return value specified for DisableWebsite")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(websiteID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WafRepo_DisableWebsite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisableWebsite'
type WafRepo_DisableWebsite_Call struct {
	*mock.Call
}

// DisableWebsite is a helper method to define mock.On call
//   - websiteID uint
func (_e *WafRepo_Expecter) DisableWebsite(websiteID interface{}) *WafRepo_DisableWebsite_Call {
	return &WafRepo_DisableWebsite_Call{Call: _e.mock.On("DisableWebsite", websiteID)}
}

func (_c *WafRepo_DisableWebsite_Call) Run(run func(websiteID uint)) *WafRepo_DisableWebsite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *WafRepo_DisableWebsite_Call) Return(_a0 error) *WafRepo_DisableWebsite_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WafRepo_DisableWebsite_Call) RunAndReturn(run func(uint) error) *WafRepo_DisableWebsite_Call {
	_c.Call.Return(run)
	return _c
}

// EnableWebsite provides a mock function with given fields: req
func (_m *WafRepo) EnableWebsite(req *request.WafWebsiteToggle) error {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for EnableWebsite")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*request.WafWebsiteToggle) error); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WafRepo_EnableWebsite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableWebsite'
type WafRepo_EnableWebsite_Call struct {
	*mock.Call
}

// EnableWebsite is a helper method to define mock.On call
//   - req *request.WafWebsiteToggle
func (_e *WafRepo_Expecter) EnableWebsite(req interface{}) *WafRepo_EnableWebsite_Call {
	return &WafRepo_EnableWebsite_Call{Call: _e.mock.On("EnableWebsite", req)}
}

func (_c *WafRepo_EnableWebsite_Call) Run(run func(req *request.WafWebsiteToggle)) *WafRepo_EnableWebsite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*request.WafWebsiteToggle))
	})
	return _c
}

func (_c *WafRepo_EnableWebsite_Call) Return(_a0 error) *WafRepo_EnableWebsite_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WafRepo_EnableWebsite_Call) RunAndReturn(run func(*request.WafWebsiteToggle) error) *WafRepo_EnableWebsite_Call {
	_c.Call.Return(run)
	return _c
}

// Events provides a mock function with given fields: query
func (_m *WafRepo) Events(query map[string]string) (interface{}, error) {
	ret := _m.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for Events")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(map[string]string) (interface{}, error)); ok {
		return rf(query)
	}
	if rf, ok := ret.Get(0).(func(map[string]string) interface{}); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(map[string]string) error); ok {
		r1 = rf(query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WafRepo_Events_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Events'
type WafRepo_Events_Call struct {
	*mock.Call
}

// Events is a helper method to define mock.On call
//   - query map[string]string
func (_e *WafRepo_Expecter) Events(query interface{}) *WafRepo_Events_Call {
	return &WafRepo_Events_Call{Call: _e.mock.On("Events", query)}
}

func (_c *WafRepo_Events_Call) Run(run func(query map[string]string)) *WafRepo_Events_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[string]string))
	})
	return _c
}

func (_c *WafRepo_Events_Call) Return(_a0 interface{}, _a1 error) *WafRepo_Events_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WafRepo_Events_Call) RunAndReturn(run func(map[string]string) (interface{}, error)) *WafRepo_Events_Call {
	_c.Call.Return(run)
	return _c
}

// GetPolicy provides a mock function with given fields: policyID
func (_m *WafRepo) GetPolicy(policyID string) (interface{}, error) {
	ret := _m.Called(policyID)

	if len(ret) == 0 {
		panic("no return value specified for GetPolicy")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (interface{}, error)); ok {
		return rf(policyID)
	}
	if rf, ok := ret.Get(0).(func(string) interface{}); ok {
		r0 = rf(policyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(policyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WafRepo_GetPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPolicy'
type WafRepo_GetPolicy_Call struct {
	*mock.Call
}

// GetPolicy is a helper method to define mock.On call
//   - policyID string
func (_e *WafRepo_Expecter) GetPolicy(policyID interface{}) *WafRepo_GetPolicy_Call {
	return &WafRepo_GetPolicy_Call{Call: _e.mock.On("GetPolicy", policyID)}
}

func (_c *WafRepo_GetPolicy_Call) Run(run func(policyID string)) *WafRepo_GetPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *WafRepo_GetPolicy_Call) Return(_a0 interface{}, _a1 error) *WafRepo_GetPolicy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WafRepo_GetPolicy_Call) RunAndReturn(run func(string) (interface{}, error)) *WafRepo_GetPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// GetPolicyStatus provides a mock function with given fields: policyID
func (_m *WafRepo) GetPolicyStatus(policyID string) (interface{}, error) {
	ret := _m.Called(policyID)

	if len(ret) == 0 {
		panic("no return value specified for GetPolicyStatus")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (interface{}, error)); ok {
		return rf(policyID)
	}
	if rf, ok := ret.Get(0).(func(string) interface{}); ok {
		r0 = rf(policyID)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(interface{})
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(policyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WafRepo_GetPolicyStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPolicyStatus'
type WafRepo_GetPolicyStatus_Call struct {
	*mock.Call
}

// GetPolicyStatus is a helper method to define mock.On call
//   - policyID string
func (_e *WafRepo_Expecter) GetPolicyStatus(policyID interface{}) *WafRepo_GetPolicyStatus_Call {
	return &WafRepo_GetPolicyStatus_Call{Call: _e.mock.On("GetPolicyStatus", policyID)}
}

func (_c *WafRepo_GetPolicyStatus_Call) Run(run func(policyID string)) *WafRepo_GetPolicyStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *WafRepo_GetPolicyStatus_Call) Return(_a0 interface{}, _a1 error) *WafRepo_GetPolicyStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WafRepo_GetPolicyStatus_Call) RunAndReturn(run func(string) (interface{}, error)) *WafRepo_GetPolicyStatus_Call {
	_c.Call.Return(run)
	return _c
}

// ListBindings provides a mock function with no fields
func (_m *WafRepo) ListBindings() ([]*biz.WafBinding, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListBindings")
	}

	var r0 []*biz.WafBinding
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*biz.WafBinding, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*biz.WafBinding); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*biz.WafBinding)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WafRepo_ListBindings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBindings'
type WafRepo_ListBindings_Call struct {
	*mock.Call
}

// ListBindings is a helper method to define mock.On call
func (_e *WafRepo_Expecter) ListBindings() *WafRepo_ListBindings_Call {
	return &WafRepo_ListBindings_Call{Call: _e.mock.On("ListBindings")}
}

func (_c *WafRepo_ListBindings_Call) Run(run func()) *WafRepo_ListBindings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *WafRepo_ListBindings_Call) Return(_a0 []*biz.WafBinding, _a1 error) *WafRepo_ListBindings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WafRepo_ListBindings_Call) RunAndReturn(run func() ([]*biz.WafBinding, error)) *WafRepo_ListBindings_Call {
	_c.Call.Return(run)
	return _c
}

// ListDecisions provides a mock function with given fields: query
func (_m *WafRepo) ListDecisions(query map[string]string) (interface{}, error) {
	ret := _m.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for ListDecisions")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(map[string]string) (interface{}, error)); ok {
		return rf(query)
	}
	if rf, ok := ret.Get(0).(func(map[string]string) interface{}); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(map[string]string) error); ok {
		r1 = rf(query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WafRepo_ListDecisions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDecisions'
type WafRepo_ListDecisions_Call struct {
	*mock.Call
}

// ListDecisions is a helper method to define mock.On call
//   - query map[string]string
func (_e *WafRepo_Expecter) ListDecisions(query interface{}) *WafRepo_ListDecisions_Call {
	return &WafRepo_ListDecisions_Call{Call: _e.mock.On("ListDecisions", query)}
}

func (_c *WafRepo_ListDecisions_Call) Run(run func(query map[string]string)) *WafRepo_ListDecisions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[string]string))
	})
	return _c
}

func (_c *WafRepo_ListDecisions_Call) Return(_a0 interface{}, _a1 error) *WafRepo_ListDecisions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WafRepo_ListDecisions_Call) RunAndReturn(run func(map[string]string) (interface{}, error)) *WafRepo_ListDecisions_Call {
	_c.Call.Return(run)
	return _c
}

// ListExclusions provides a mock function with given fields: policyID
func (_m *WafRepo) ListExclusions(policyID string) (interface{}, error) {
	ret := _m.Called(policyID)

	if len(ret) == 0 {
		panic("no return value specified for ListExclusions")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (interface{}, error)); ok {
		return rf(policyID)
	}
	if rf, ok := ret.Get(0).(func(string) interface{}); ok {
		r0 = rf(policyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(policyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WafRepo_ListExclusions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListExclusions'
type WafRepo_ListExclusions_Call struct {
	*mock.Call
}

// ListExclusions is a helper method to define mock.On call
//   - policyID string
func (_e *WafRepo_Expecter) ListExclusions(policyID interface{}) *WafRepo_ListExclusions_Call {
	return &WafRepo_ListExclusions_Call{Call: _e.mock.On("ListExclusions", policyID)}
}

func (_c *WafRepo_ListExclusions_Call) Run(run func(policyID string)) *WafRepo_ListExclusions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *WafRepo_ListExclusions_Call) Return(_a0 interface{}, _a1 error) *WafRepo_ListExclusions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WafRepo_ListExclusions_Call) RunAndReturn(run func(string) (interface{}, error)) *WafRepo_ListExclusions_Call {
	_c.Call.Return(run)
	return _c
}

// ListPolicies provides a mock function with no fields
func (_m *WafRepo) ListPolicies() (interface{}, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListPolicies")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func() (interface{}, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WafRepo_ListPolicies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPolicies'
type WafRepo_ListPolicies_Call struct {
	*mock.Call
}

// ListPolicies is a helper method to define mock.On call
func (_e *WafRepo_Expecter) ListPolicies() *WafRepo_ListPolicies_Call {
	return &WafRepo_ListPolicies_Call{Call: _e.mock.On("ListPolicies")}
}

func (_c *WafRepo_ListPolicies_Call) Run(run func()) *WafRepo_ListPolicies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *WafRepo_ListPolicies_Call) Return(_a0 interface{}, _a1 error) *WafRepo_ListPolicies_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WafRepo_ListPolicies_Call) RunAndReturn(run func() (interface{}, error)) *WafRepo_ListPolicies_Call {
	_c.Call.Return(run)
	return _c
}

// Stats provides a mock function with given fields: query
func (_m *WafRepo) Stats(query map[string]string) (interface{}, error) {
	ret := _m.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(map[string]string) (interface{}, error)); ok {
		return rf(query)
	}
	if rf, ok := ret.Get(0).(func(map[string]string) interface{}); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(map[string]string) error); ok {
		r1 = rf(query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WafRepo_Stats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stats'
type WafRepo_Stats_Call struct {
	*mock.Call
}

// Stats is a helper method to define mock.On call
//   - query map[string]string
func (_e *WafRepo_Expecter) Stats(query interface{}) *WafRepo_Stats_Call {
	return &WafRepo_Stats_Call{Call: _e.mock.On("Stats", query)}
}

func (_c *WafRepo_Stats_Call) Run(run func(query map[string]string)) *WafRepo_Stats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[string]string))
	})
	return _c
}

func (_c *WafRepo_Stats_Call) Return(_a0 interface{}, _a1 error) *WafRepo_Stats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WafRepo_Stats_Call) RunAndReturn(run func(map[string]string) (interface{}, error)) *WafRepo_Stats_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePolicy provides a mock function with given fields: policyID, body
func (_m *WafRepo) UpdatePolicy(policyID string, body interface{}) (interface{}, error) {
	ret := _m.Called(policyID, body)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePolicy")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(string, interface{}) (interface{}, error)); ok {
		return rf(policyID, body)
	}
	if rf, ok := ret.Get(0).(func(string, interface{}) interface{}); ok {
		r0 = rf(policyID, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(string, interface{}) error); ok {
		r1 = rf(policyID, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WafRepo_UpdatePolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePolicy'
type WafRepo_UpdatePolicy_Call struct {
	*mock.Call
}

// UpdatePolicy is a helper method to define mock.On call
//   - policyID string
//   - body interface{}
func (_e *WafRepo_Expecter) UpdatePolicy(policyID interface{}, body interface{}) *WafRepo_UpdatePolicy_Call {
	return &WafRepo_UpdatePolicy_Call{Call: _e.mock.On("UpdatePolicy", policyID, body)}
}

func (_c *WafRepo_UpdatePolicy_Call) Run(run func(policyID string, body interface{})) *WafRepo_UpdatePolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(interface{}))
	})
	return _c
}

func (_c *WafRepo_UpdatePolicy_Call) Return(_a0 interface{}, _a1 error) *WafRepo_UpdatePolicy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WafRepo_UpdatePolicy_Call) RunAndReturn(run func(string, interface{}) (interface{}, error)) *WafRepo_UpdatePolicy_Call {
	_c.Call.Return(run)
	return _c
}

// NewWafRepo creates a new instance of WafRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWafRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *WafRepo {
	mock := &WafRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
